<a href="https://colab.research.google.com/github/LaraSofiaLopes/Numerical-Analysis/blob/master/Lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **LAB 6**
### Lara Lopes

### **Task 2**

**1)**

    4x1 − x2 + x3 = 8
    2x1 + 5x2 + 2x3 = 3
    x1 + 2x2 + 4x3 = 11

Multiply equation 3 by -2 and add equation 2: 

    4x1 − x2 + x3 = 8
    2x1 + 5x2 + 2x3 = 3
    0x1 + 1x2 + -6x3 = -19

Multiply equation 2 by -2 and add equation 1:

    4x1 − x2 + x3 = 8
    0x1 + -11x2 + -3x3 = 2
    0x1 + 1x2 + -6x3 = -19

Multiply equation 3 by 11 and add equation 2:

    4x1 − x2 + x3 = 8
    0x1 + -11x2 + -3x3 = 2
    0x1 + 0x2 + -69x3 = -207

Final results:

    x3 = 3
    x2 = -1
    x1 = 1

**2)**
 
    4x1 − x2 + 2x3 = 9
    2x1 + 4x2 - x3 = -5
    x1 + x2 - 3x3 = -9

Multiply equation 3 by -2 and add equation 2:

    4x1 − x2 + 2x3 = 9
    2x1 + 4x2 - x3 = -5
    0x1 + 2x2 + 5x3 = 13

Multiply equation 2 by -2 and add equation 1:

    4x1 − x2 + 2x3 = 9
    0x1 - 9x2 + 4x3 = 19
    0x1 + 2x2 + 5x3 = 13

Multiply equation 3 by 9 and equation 2 and add equation 2 to equation 3:

    4x1 − x2 + 2x3 = 9
    0x1 - 9x2 + 4x3 = 19
    0x1 + 0x2 + 53x3 = 155

Final result: 

    x3 = 3
    x2 = -1
    x1 = 1

### **Task 3**

In [1]:
# Gaussian elimination

import scipy 
import scipy.linalg
import numpy as np
import copy

def linearsolver(A,b):
  n = len(A)
  M = A

  i = 0
  for x in M:
   x.append(b[i])
   i += 1


  for k in range(n):
   # first pivoting
   for i in range(k,n):
     if abs(M[i][k]) > abs(M[k][k]):
        M[k], M[i] = M[i],M[k]
     else:
        pass
   
   # Gaussian elimination in loop 
   for j in range(k+1,n):
       q = float(M[j][k]) / M[k][k]
       for m in range(k, n+1):
          # M_jm = M_jm - M_jk / M_kk *M_km
          M[j][m] -=  q * M[k][m]

  x = [0 for i in range(n)]       # x = [0, 0, .... , 0]

  # calculating x
  x[n-1] =float(M[n-1][n])/M[n-1][n-1]
  for i in range (n-1,-1,-1):
    z = 0
    for j in range(i+1,n):
        z = z  + float(M[i][j])*x[j]
    x[i] = float(M[i][n] - z)/M[i][i]
  return x


A = [[4, -1, 1], [2, 5, 2], [1, 2, 4]]
b = [8, 3, 11]

A1 = copy.deepcopy(A)
x = linearsolver(A1, b)

print("Result with our linearsolver:")
print(np.array(A)," * x = ",np.array(b))
print("Solution:")
print(x)


x = scipy.linalg.solve(A,b)

print(" ")
print("Result with linalg.solve:")
print(np.array(A)," * x = ",np.array(b))
print("Solution:")
print(x)

Result with our linearsolver:
[[ 4 -1  1]
 [ 2  5  2]
 [ 1  2  4]]  * x =  [ 8  3 11]
Solution:
[1.0, -1.0, 3.0]
 
Result with linalg.solve:
[[ 4 -1  1]
 [ 2  5  2]
 [ 1  2  4]]  * x =  [ 8  3 11]
Solution:
[ 1. -1.  3.]


In [2]:
# Gaussian elimination

import scipy 
import scipy.linalg
import numpy as np
import copy

def linearsolver(A,b):
  n = len(A)
  M = A

  i = 0
  for x in M:
   x.append(b[i])
   i += 1


  for k in range(n):
   # first pivoting
   for i in range(k,n):
     if abs(M[i][k]) > abs(M[k][k]):
        M[k], M[i] = M[i],M[k]
     else:
        pass
   
   # Gaussian elimination in loop 
   for j in range(k+1,n):
       q = float(M[j][k]) / M[k][k]
       for m in range(k, n+1):
          # M_jm = M_jm - M_jk / M_kk *M_km
          M[j][m] -=  q * M[k][m]

  x = [0 for i in range(n)]       # x = [0, 0, .... , 0]

  # calculating x
  x[n-1] =float(M[n-1][n])/M[n-1][n-1]
  for i in range (n-1,-1,-1):
    z = 0
    for j in range(i+1,n):
        z = z  + float(M[i][j])*x[j]
    x[i] = float(M[i][n] - z)/M[i][i]
  return x

A = [[4, -1, 2], [2, 4, -1], [1, 1, -3]]
b = [9, -5, -9]

A1 = copy.deepcopy(A)
x = linearsolver(A1, b)

print("Result with our linearsolver:")
print(np.array(A)," * x = ",np.array(b))
print("Solution:")
print(x)


x = scipy.linalg.solve(A,b)

print(" ")
print("Result with linalg.solve:")
print(np.array(A)," * x = ",np.array(b))
print("Solution:")
print(x)

Result with our linearsolver:
[[ 4 -1  2]
 [ 2  4 -1]
 [ 1  1 -3]]  * x =  [ 9 -5 -9]
Solution:
[0.5849056603773586, -0.8113207547169813, 2.924528301886792]
 
Result with linalg.solve:
[[ 4 -1  2]
 [ 2  4 -1]
 [ 1  1 -3]]  * x =  [ 9 -5 -9]
Solution:
[ 0.58490566 -0.81132075  2.9245283 ]


We found the same solution with the implemented program and with scipy.linalg.solve(A,b).

### **Task 4**

In [4]:
# LU decomposition

import numpy as np

def LU_partial_decomposition(matrix):
    n, m = matrix.shape
    P = np.identity(n)
    L = np.identity(n)
    U = matrix.copy()
    PF = np.identity(n)
    LF = np.zeros((n,n))
    for k in range(0, n - 1):
        index = np.argmax(abs(U[k:,k]))
        index = index + k 

        # here we do pivoting
        if index != k:
            P = np.identity(n)
            P[[index,k],k:n] = P[[k,index],k:n]
            U[[index,k],k:n] = U[[k,index],k:n] 
            PF = np.dot(P,PF)
            LF = np.dot(P,LF)
        # and here decomposition    
        L = np.identity(n)
        for j in range(k+1,n):
            L[j,k] = -(U[j,k] / U[k,k])
            LF[j,k] = (U[j,k] / U[k,k])
        U = np.dot(L,U)
    np.fill_diagonal(LF, 1)
    return PF, LF, U

   
# Usage
A = [[1, 2, 1], [1, -2, 2], [2, 12, -2]]
A = np.array(A)
P1, L1, U1 = LU_partial_decomposition(A)

# Scipy
import scipy
import scipy.linalg
#LU decomposition using linalg.lu library function
P2, L2, U2 = scipy.linalg.lu(A) # P2 = P2.T  

print("Input array:")
print(A)
print(" ")
print("Result. Pivoting array:")
print(P1)
print("L and U arrays:")
print(L1,"\n", U1)
print(" ")
print("Result using linalg.lu function. Pivoting array:")
print(P2.T)  # transponed array
print("L and U arrays:")
print(L2,"\n", U2)

Input array:
[[ 1  2  1]
 [ 1 -2  2]
 [ 2 12 -2]]
 
Result. Pivoting array:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L and U arrays:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.5 1. ]] 
 [[ 2.  12.  -2. ]
 [ 0.  -8.   3. ]
 [ 0.   0.   0.5]]
 
Result using linalg.lu function. Pivoting array:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
L and U arrays:
[[1.  0.  0. ]
 [0.5 1.  0. ]
 [0.5 0.5 1. ]] 
 [[ 2.  12.  -2. ]
 [ 0.  -8.   3. ]
 [ 0.   0.   0.5]]
